name: Simple Logging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-pack-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal

      - name: Pack
        run: dotnet pack Simple.Logging/Simple.Logging.csproj -p:PackageID=Simple.Serilog.Logging -c Release --no-restore --no-build -p:Version=1.0.${{github.run_number}} -o .

      - name: Push to NuGet
        run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}

